# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./profiles/player.nix
    ];
  nixpkgs.config.allowUnfree = true;
  # Use the GRUB 2 boot loader.
  boot.loader.grub = {
    enable = true;
    version = 2;
    device = "/dev/sda";
  };


  fileSystems = {
    "/" = { device = "/dev/sda1"; fsType = "ext4"; };
    "/mnt/Zeus" = { device = "/dev/sdb1"; fsType = "btrfs"; };
    "/mnt/Constantine" = { device = "/dev/sdc1"; fsType = "btrfs"; };
    "/home/pxc/.local/mnt/Constantine" = { device = "/mnt/Constantine"; fsType = "bind"; };
  };

  networking.hostName = "mutter"; # Define your hostname.

  environment.systemPackages = with pkgs; [
  ];

  # The NixOS release to be compatible with for stateful data such as databases.
  system.stateVersion = "16.03";

  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.opengl.driSupport32Bit = true;

  services.xserver.deviceSection = ''
    #Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "GeForce GTX 750 Ti"
  '';

  # based on configuration generated by nvidia-config
  services.xserver.monitorSection = ''
    # HorizSync source: edid, VertRefresh source: edid
    Identifier     "Monitor0"
    VendorName     "Seiki"
    ModelName      "SEK SE42UMS"
    HorizSync       30.0 - 80.0
    VertRefresh     50.0 - 75.0
    Option         "DPMS" "False" # this TV sucks; can't do DPMS
    DisplaySize    894 563
  '';

  hardware.bluetooth.enable = true;
  hardware.pulseaudio.package = pkgs.pulseaudioFull;
  networking.networkmanager.enable = true;

  services.xserver.displayManager.sddm.autoLogin = {
    enable = true;
    user = "pxc";
    relogin = true;
  };
}
