# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/dad5a4c3-4a2a-4bd7-9091-461c258ef3ee";
      fsType = "ext4";
      options = [ "defaults" "noatime" ];
    };

    "/nix/store" = {
      device = "/dev/disk/by-uuid/18ff7c89-009b-47df-98ea-5fcb3d152833";
      fsType = "ext4";
      options = [ "defaults" "noatime" ];
    };

    "/boot/efi" = {
      device = "/dev/disk/by-uuid/B81B-593A";
      fsType = "vfat";
    };

    "/var/lib/libvirt/images" = {
      device = "/dev/disk/by-uuid/1f6dca6f-17c7-4134-8f9b-ca1c4f7c8fa1";
      fsType = "ext4";
      options = [ "defaults" "noatime" ];
    };

    "/var/lib/vbox/images" = {
      device = "/dev/disk/by-uuid/8a95a69b-4b03-4bb6-9e04-1a6902e77436";
      fsType = "ext4";
      options = [ "defaults" "noatime" ];
    };

    "/data/shared/Common" = {
      device = "/dev/disk/by-uuid/23ade87c-eea2-4336-9195-009f13ba00a1";
      fsType = "ext4";
      options = [ "defaults" "noatime" ];
    };

    ### bind mounts ###
    "/home/pxc/.dotfiles/config/nixpkgs" = {
      device = "/etc/nixos";
      options = [ "bind" ];
      noCheck = true;
    };

    # shared user data
    "/home/pxc/.dotfiles" = {
      device = "/data/shared/Common/per-user/pxc/dotfiles";
      options = [ "bind" ];
      noCheck = true;
    };

    # mount in ~ directory for access via Steam, since ~ is in the NixOS Steam
    # chroot
    "/home/pxc/.local/data/Games" = {
      device = "/data/shared/Common/Games";
      options = [ "bind" ];
      noCheck = true;
    };

    "/home/pxc/Downloads" = {
      device = "/data/shared/Common/per-user/pxc/Downloads";
      options = [ "bind" ];
      noCheck = true;
      neededForBoot = false;
    };

    "/home/pxc/Documents" = {
      device = "/data/shared/Common/per-user/pxc/Documents";
      options = [ "bind" ];
      noCheck = true;
      neededForBoot = false;
    };

    "/home/pxc/Music" = {
      device = "/data/shared/Common/per-user/pxc/Music";
      options = [ "bind" ];
      noCheck = true;
      neededForBoot = false;
    };

    "/home/pxc/Playground" = {
      device = "/data/shared/Common/per-user/pxc/Playground";
      options = [ "bind" ];
      noCheck = true;
      neededForBoot = false;
    };

    "/home/pxc/Videos" = {
      device = "/data/shared/Common/per-user/pxc/Videos";
      options = [ "bind" ];
      noCheck = true;
      neededForBoot = false;
    };

    "/data/foreign-os/openSUSE" = {
      device = "/dev/disk/by-uuid/2f953f0a-64d3-46ec-80d8-66179ce15091";
      fsType = "btrfs";
      noCheck = true;
      neededForBoot = false;
    };

    "data/foreign-os/openSUSE/boot/efi" = {
      device = "/dev/disk/by-uuid/B81B-593A";
      fsType = "vfat";
    };

    "/data/foreign-os/openSUSE/home" = {
      device = "/dev/disk/by-uuid/e168d489-ab14-4237-8270-c371c9d337f0";
      fsType = "ext4";
      noCheck = true;
      neededForBoot = false;
    };

  };


  swapDevices = [ { device = "/dev/disk/by-uuid/30136dbd-a7e0-4763-b99f-e3e0d255512a"; } ];

  nix.maxJobs = lib.mkDefault 4;
}
